server:
  port: 8080
  error:
    include-binding-errors: always
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: postgres
    password: ninja
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  banner:
    location: banner.txt
  security:
    user:
      name: user
      password: password

